version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - '**/*'
  base-directory: 'build'