version: 0.2
phases:
    pre_build:
        commands:
           # - n 18
           # - node -v
           # - npm -v
            - npm install -g sonarqube-scanner
            - npm i          
    build:
        commands:
            - npm run build .env.production
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
cache:
    paths:
        - 'node_modules/**/*'