version: 0.2
phases:
    pre_build:
        commands:
            # - n 18
            # - node -v
            # - npm -v
            - npm install -g sonarqube-scanner
            - npm i
    build:
        commands:
            # - codebuild-breakpoint
            - npm run test:coverage || true

            - sonar-scanner -Dsonar.sources=src -Dsonar.projectKey=dms-ui-application -Dsonar.host.url=http://sonarqube.mahindradealerrise.com:9000/ -Dsonar.login=squ_aab97ec89b8281e198e7b72fa13a8d4f3dca996a
            #- npm run build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
cache:
    paths:
        - 'node_modules/**/*'
