version: 0.2
phases:
    pre_build:
        commands:
            # - n 18
            # - node -v
            # - npm -v
            - npm install -g sonarqube-scanner
            - npm i --force
    build:
        commands:
            # - codebuild-breakpoint
            - npm run test:coverage || true

            - sonar-scanner -Dsonar.sources=src -Dsonar.projectKey=dms-ui-application -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_TOKEN}
            #- npm run build
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
cache:
    paths:
        - 'node_modules/**/*'
env:
    secrets-manager:
        SONAR_TOKEN: 'arn:aws:secretsmanager:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:secret:sonar-coverage-command-skip-zZ1e0B:SONAR_TOKEN'
        SONAR_URL: 'arn:aws:secretsmanager:${AWS_DEFAULT_REGION}:${AWS_ACCOUNT_ID}:secret:sonar-coverage-command-skip-zZ1e0B:SONAR_URL'
