version: 0.2
phases:
    pre_build:
        commands:
            # - n 18
            # - node -v
            # - npm -v
            - npm install -g sonarqube-scanner
            - npm i --force
    build:
        commands:
            - npm run build .env.development
    post_build:
        commands:
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
cache:
    paths:
        - 'node_modules/**/*'
