version: 0.2
phases:
  pre_build:
    commands:
      - npm i --force
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - npm run build .env.production
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Build is completed
artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  name: ad-qa-ui-artifacts