version: 0.2
phases:
    pre_build:
        commands:
            - npm i          
    build:
        commands:
            # - codebuild-breakpoint   
            # - npm run coverage
            - npm run build
            - sonar-scanner \
                -Dsonar.projectKey=dms-ui-application \
                -Dsonar.host.url=http://10.168.15.236:9000/ \
                -Dsonar.login=squ_f9e7dfe0aeeff99754b4cb402800e65b4fb37d0f
            # - sonar-scanner -Dsonar.sources=src -Dsonar.projectKey=dms-ui-application -Dsonar.host.url=http://10.168.15.236:9000/ -Dsonar.login=squ_f9e7dfe0aeeff99754b4cb402800e65b4fb37d0f
    post_build:
        commands:
            - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
    files:
        - '**/*'
    base-directory: 'build'
cache:
    paths:
        - 'node_modules/**/*'
#reports:
 #   reports-test:
 #       files:
 #           - 'coverage/clover.xml'
   #     file-format: 'CLOVERXML'