export const dealerData = [
    {
        id: '01f8be90-831d-411b-b14c-7aba78df57c8',
        attributeId: 'PARNT',
        parentGroupCode: 'KAM01',
        parentGroupName: '',
        ownerName: 'Johny Bhai',
        contactNo: '7508699882',
        emailId: 'abcd@gmail.com',
        status: 'Y',
        type: 'Parent',
        title: 'Parent',
        shortDescription: 'Parent Short Description',
        longDescription: 'Parent Long Description',
        children: [
            {
                id: 'b8348d4a-bb58-4e44-be52-b35a84b42538',
                attributeId: 'COMP',
                parentId: '01f8be90-831d-411b-b14c-7aba78df57c8',
                code: 'MINRA',
                companyName: 'MNM',
                registeredAddressOfCompany: 'Greater Noida,UP',
                tinNumber: 'T9876543200',
                tanNumber: 'T0124234432',
                panNumber: 'ABCDE3090D',
                status: 'Y',
                type: 'Company',
                title: 'Company',
                shortDescription: 'MNM Short Description',
                longDescription: 'MNM Long Description',
                children: [
                    {
                        id: '268331d7-71fc-4870-8399-6e7ed19d81a5',
                        attributeId: 'GSTIN',
                        parentId: 'b8348d4a-bb58-4e44-be52-b35a84b42538',
                        code: 'GSTIO',
                        gstinNumber: 'GST123',
                        centerJurisdiction: 'New Delhi',
                        stateJurisdiction: 'UP',
                        dateOfRegistertion: '2022-02-11T18:30:00.000+00:00',
                        consitutionOfBusiness: 'DEMO',
                        taxPayerType: 'corp',
                        status: 'Y',
                        type: 'Gstin',
                        title: 'gsin',
                        shortDescription: 'GST IN Short Description',
                        longDescription: 'GST IN Long Description',
                        children: [
                            {
                                id: '4c7e57c0-6cc5-4576-ab1a-064f8340db57',
                                attributeId: 'LOCTN',
                                parentId: '268331d7-71fc-4870-8399-6e7ed19d81a5',
                                code: 'BOR12',
                                brancName: 'BRTEST',
                                branchAddress: 'Gautam Budh Nagar,UP',
                                city: 'Noida',
                                state: 'UP',
                                cityClassification: 'Tier-1',
                                status: 'Y',
                                type: 'Branch',
                                title: 'BRTEST',
                                shortDescription: 'BRTEST Short Description',
                                longDescription: 'BRTEST Long Description',
                            },
                        ],
                    },
                    {
                        id: '57eaa07d-a0b7-4626-9507-cae97cb8310e',
                        attributeId: 'GSTIN',
                        parentId: 'b8348d4a-bb58-4e44-be52-b35a84b42538',
                        code: 'GIO',
                        gstinNumber: 'GST123',
                        centerJurisdiction: 'New Delhi',
                        stateJurisdiction: 'UP',
                        dateOfRegistertion: '2022-02-11T18:30:00.000+00:00',
                        consitutionOfBusiness: 'DEMO',
                        taxPayerType: 'corp',
                        status: 'Y',
                        type: 'Gstin',
                        title: 'gin',
                        shortDescription: 'gin Short Description',
                        longDescription: 'gin Long Description',
                        children: [],
                    },
                    {
                        id: 'e5fcf6a9-565f-4669-b014-36c9436523e1',
                        attributeId: 'GSTIN',
                        parentId: 'b8348d4a-bb58-4e44-be52-b35a84b42538',
                        code: 'GIO1',
                        gstinNumber: 'GS123',
                        centerJurisdiction: 'New Delhi ind',
                        stateJurisdiction: 'UP IND',
                        dateOfRegistertion: '2022-02-14T18:30:00.000+00:00',
                        consitutionOfBusiness: 'DEM234',
                        taxPayerType: 'corp',
                        status: 'Y',
                        type: 'Gstin',
                        title: 'gina',
                        shortDescription: 'gina Short Description',
                        longDescription: 'gina Long Description',
                        children: [],
                    },
                ],
            },
        ],
    },
];
